# This is a basic workflow to help you get started with Actions

name: Cloud Run deployment

on:
  repository_dispatch:
    types: [artifact_uploaded]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: auth service account 2
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: install gcloud
        uses: 'google-github-actions/setup-gcloud@v3'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
      - name: Terraform Init
        run: terraform init
      - name: Update Variables
        run: |
          echo 'tag = "${{ github.event.client_payload.run_id }}"' >> terraform.tfvars
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -out=tfplan
      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
