# This is a basic workflow to help you get started with Actions

name: Cloud Run deployment

on:
  repository_dispatch:
    types: [artifact_uploaded]
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID'
        required: true
        default: 'latest'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: auth service account 2
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - name: install gcloud
        uses: 'google-github-actions/setup-gcloud@v3'
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
      - name: Terraform Init
        run: terraform init
      - name: Update Variables from event
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo 'tag = "${{ github.event.client_payload.run_id }}"' >> terraform.tfvars
      - name: Update Variables from inputs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo -e "\n" >> terraform.tfvars
          echo 'tag = "${{ github.event.inputs.run_id }}"' >> terraform.tfvars
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -out=plan.out
      - name: Apply Terraform
        run: terraform apply -auto-approve
