# This is a basic workflow to help you get started with Actions

name: Cloud Run deployment

on:
  repository_dispatch:
    types: [artifact_uploaded]
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  gcloud-setup:
    runs-on: ubuntu-latest
    needs: [checkout]
    steps:
    - name: auth service account 2
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
    - name: install gcloud
      uses: 'google-github-actions/setup-gcloud@v3'
  terraform-setup:
    runs-on: ubuntu-latest
    needs: [gcloud-setup]
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5
      - name: Terraform Init
        run: terraform init
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform plan
        run: terraform plan -out=tfplan -var="tag=${{ github.event.client_payload.run_id }}"
  terraform-apply:
    runs-on: ubuntu-latest
    needs: [terraform-setup]
    steps:
      - name: Apply Terraform
        run: terraform apply -auto-approve tfplan
